-- MySQL Script generated by MySQL Workbench
-- Sun May 28 14:52:48 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `usuario` VARCHAR(50) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `rol` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`usuario`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`libros`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`libros` ;

CREATE TABLE IF NOT EXISTS `mydb`.`libros` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `isbn` VARCHAR(60) NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `autor` VARCHAR(45) NOT NULL,
  `editorial` VARCHAR(50) NOT NULL,
  `paginas` INT NOT NULL,
  `disponible` BIT NOT NULL,
  `url_imagen` VARCHAR(500) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`equipos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`equipos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`equipos` (
  `serie` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `fabricante` VARCHAR(45) NOT NULL,
  `disponible` BIT NOT NULL,
  `url_imagen` VARCHAR(500) NULL,
  PRIMARY KEY (`serie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sala`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`sala` ;

CREATE TABLE IF NOT EXISTS `mydb`.`sala` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `disponible` BIT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`prestamos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`prestamos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`prestamos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(50) NOT NULL,
  `equipos_serie` INT NULL,
  `libros_id` INT NULL,
  `sala_id` INT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `fecha_vencimiento` DATETIME NOT NULL,
  `fecha_prestamo` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `reportecada` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_prestamos_equipos1_idx` (`equipos_serie` ASC),
  INDEX `fk_prestamos_libros1_idx` (`libros_id` ASC),
  INDEX `fk_prestamos_sala1_idx` (`sala_id` ASC),
  INDEX `fk_prestamos_usuarios1_idx` (`usuario` ASC),
  CONSTRAINT `fk_prestamos_equipos1`
    FOREIGN KEY (`equipos_serie`)
    REFERENCES `mydb`.`equipos` (`serie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prestamos_libros1`
    FOREIGN KEY (`libros_id`)
    REFERENCES `mydb`.`libros` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prestamos_sala1`
    FOREIGN KEY (`sala_id`)
    REFERENCES `mydb`.`sala` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prestamos_usuarios1`
    FOREIGN KEY (`usuario`)
    REFERENCES `mydb`.`usuarios` (`usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reportes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`reportes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`reportes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(45) NOT NULL,
  `comentarios` VARCHAR(255) NULL,
  `prestamos_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_reportes_prestamos1_idx` (`prestamos_id` ASC),
  CONSTRAINT `fk_reportes_prestamos1`
    FOREIGN KEY (`prestamos_id`)
    REFERENCES `mydb`.`prestamos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`eventos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`eventos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`eventos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fechainicio` DATETIME NOT NULL,
  `fechafin` DATETIME NOT NULL,
  `lugar` VARCHAR(45) NULL,
  `sala_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_eventos_sala1_idx` (`sala_id` ASC),
  CONSTRAINT `fk_eventos_sala1`
    FOREIGN KEY (`sala_id`)
    REFERENCES `mydb`.`sala` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
