-- MySQL Script generated by MySQL Workbench
-- Sun May 28 22:42:13 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `usuario` VARCHAR(50) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `rol` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`usuario`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`libros`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`libros` ;

CREATE TABLE IF NOT EXISTS `mydb`.`libros` (
  `isbn` VARCHAR(60) NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `autor` VARCHAR(45) NOT NULL,
  `editorial` VARCHAR(50) NOT NULL,
  `paginas` INT NOT NULL,
  `disponibles` INT NOT NULL,
  `total` INT NOT NULL,
  `url_imagen` VARCHAR(500) NULL,
  PRIMARY KEY (`isbn`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`equipos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`equipos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`equipos` (
  `nombre` VARCHAR(45) NOT NULL,
  `serie` INT NOT NULL,
  `fabricante` VARCHAR(45) NOT NULL,
  `disponibles` INT NOT NULL,
  `total` INT NOT NULL,
  `url_imagen` VARCHAR(500) NULL,
  PRIMARY KEY (`nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sala`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`sala` ;

CREATE TABLE IF NOT EXISTS `mydb`.`sala` (
  `nombre` VARCHAR(45) NOT NULL,
  `disponibles` INT NOT NULL,
  `total` INT NOT NULL,
  PRIMARY KEY (`nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`solicitudes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`solicitudes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`solicitudes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(50) NOT NULL,
  `equipos_nombre` VARCHAR(45) NULL,
  `libros_isbn` VARCHAR(60) NULL,
  `sala_nombre` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `fecha_prestamo` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_vencimiento` DATETIME NULL,
  `reportecada` INT NULL,
  `estado` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_prestamos_usuarios1_idx` (`usuario` ASC),
  INDEX `fk_solicitudes_libros1_idx` (`libros_isbn` ASC),
  INDEX `fk_solicitudes_sala1_idx` (`sala_nombre` ASC),
  INDEX `fk_solicitudes_equipos1_idx` (`equipos_nombre` ASC),
  CONSTRAINT `fk_prestamos_usuarios1`
    FOREIGN KEY (`usuario`)
    REFERENCES `mydb`.`usuarios` (`usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitudes_libros1`
    FOREIGN KEY (`libros_isbn`)
    REFERENCES `mydb`.`libros` (`isbn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitudes_sala1`
    FOREIGN KEY (`sala_nombre`)
    REFERENCES `mydb`.`sala` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitudes_equipos1`
    FOREIGN KEY (`equipos_nombre`)
    REFERENCES `mydb`.`equipos` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reportes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`reportes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`reportes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `solicitudes_id` INT NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `comentarios` VARCHAR(255) NULL,
  `fecha_reporte` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_reportes_solicitudes1_idx` (`solicitudes_id` ASC),
  CONSTRAINT `fk_reportes_solicitudes1`
    FOREIGN KEY (`solicitudes_id`)
    REFERENCES `mydb`.`solicitudes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`eventos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`eventos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`eventos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fechainicio` DATETIME NOT NULL,
  `fechafin` DATETIME NOT NULL,
  `lugar` VARCHAR(45) NULL,
  `sala_nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_eventos_sala1_idx` (`sala_nombre` ASC),
  CONSTRAINT `fk_eventos_sala1`
    FOREIGN KEY (`sala_nombre`)
    REFERENCES `mydb`.`sala` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`suscripciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`suscripciones` ;

CREATE TABLE IF NOT EXISTS `mydb`.`suscripciones` (
  `usuario` VARCHAR(50) NOT NULL,
  `eventos_id` INT NOT NULL,
  PRIMARY KEY (`usuario`, `eventos_id`),
  INDEX `fk_usuarios_has_eventos_eventos1_idx` (`eventos_id` ASC),
  INDEX `fk_usuarios_has_eventos_usuarios1_idx` (`usuario` ASC),
  CONSTRAINT `fk_usuarios_has_eventos_usuarios1`
    FOREIGN KEY (`usuario`)
    REFERENCES `mydb`.`usuarios` (`usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_has_eventos_eventos1`
    FOREIGN KEY (`eventos_id`)
    REFERENCES `mydb`.`eventos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


/* INSERTS */

-- Equipos
INSERT INTO `equipos`(`nombre`, `fabricante`, `disponibles`, `total`, `url_imagen`) VALUES ('XPS','Dell',3,4,'http://i.dell.com/sites/imagecontent/consumer/merchandizing/en/PublishingImages/Franchise-category/xps-family-polaris-sub-cat-franchise-laptops-mod-06.jpg');
INSERT INTO `equipos`(`nombre`, `fabricante`, `disponibles`, `total`) VALUES ('Zenbook','Asus',4,4);
